"""
Catalogue rows, transcribed from the frontend's original ``lib/catalog.ts``.

Kept as plain data so ``seed_catalog`` is the only writer and the tiers cannot
drift. The rename on the way in is deliberate: ``mode`` becomes ``kind``,
``group`` becomes ``grouping``, ``promptFragment`` becomes ``fragment``.
"""

from __future__ import annotations

from typing import Any

MODELS: list[dict[str, Any]] = [
    {
        "id": "seedance-2-5",
        "name": "Seedance 2.5",
        "kind": "video",
        "tagline": "The most advanced video model",
        "cost": 17,
        "badge": "new",
        "strengths": ["Physical motion", "Long takes", "Character consistency"],
    },
    {
        "id": "seedance-2-0",
        "name": "Seedance 2.0",
        "kind": "video",
        "tagline": "4K output, the proven workhorse",
        "cost": 14,
        "badge": None,
        "strengths": ["4K", "Reliable", "Fast"],
    },
    {
        "id": "kling-3-0",
        "name": "Kling 3.0",
        "kind": "video",
        "tagline": "Strong physics and character motion",
        "cost": 15,
        "badge": None,
        "strengths": ["Physics", "Faces", "Action"],
    },
    {
        "id": "sora-2",
        "name": "Sora 2",
        "kind": "video",
        "tagline": "Native audio and long continuous shots",
        "cost": 20,
        "badge": None,
        "strengths": ["Native audio", "Long shots", "Coherence"],
    },
    {
        "id": "veo-3-1",
        "name": "Veo 3.1",
        "kind": "video",
        "tagline": "Cinematic realism with sound",
        "cost": 19,
        "badge": None,
        "strengths": ["Realism", "Sound", "Lighting"],
    },
    {
        "id": "wan-2-6",
        "name": "WAN 2.6",
        "kind": "video",
        "tagline": "Fast open-weight video",
        "cost": 9,
        "badge": None,
        "strengths": ["Speed", "Cheap", "Stylised"],
    },
    {
        "id": "grok-imagine-1-5",
        "name": "Grok Imagine 1.5",
        "kind": "video",
        "tagline": "Fast, stylised motion",
        "cost": 8,
        "badge": None,
        "strengths": ["Speed", "Stylised", "Surreal"],
    },
    {
        "id": "gemini-omni-flash",
        "name": "Gemini Omni Flash",
        "kind": "video",
        "tagline": "Fastest turnaround of the line-up",
        "cost": 7,
        "badge": None,
        "strengths": ["Fastest", "Drafts", "Iteration"],
    },
    {
        "id": "cinema-studio-4",
        "name": "Cinema Studio 4.0",
        "kind": "video",
        "tagline": "Create cinematic scenes effortlessly",
        "cost": 22,
        "badge": "pro",
        "strengths": ["Multi-shot scenes", "Lighting control", "Film grain"],
    },
    {
        "id": "nano-banana-pro",
        "name": "Nano Banana Pro",
        "kind": "image",
        "tagline": "Generate high-quality visuals",
        "cost": 2,
        "badge": "new",
        "strengths": ["Text rendering", "Composition", "Speed"],
    },
    {
        "id": "flux-2",
        "name": "Flux 2",
        "kind": "image",
        "tagline": "Sharp detail and tight prompt adherence",
        "cost": 3,
        "badge": None,
        "strengths": ["Detail", "Adherence", "Typography"],
    },
    {
        "id": "seedream-5",
        "name": "Seedream 5",
        "kind": "image",
        "tagline": "Photoreal composition",
        "cost": 3,
        "badge": None,
        "strengths": ["Photoreal", "Composition", "Depth"],
    },
    {
        "id": "gpt-image-2",
        "name": "GPT Image 2",
        "kind": "image",
        "tagline": "Sharper edits with more natural light and texture",
        "cost": 3,
        "badge": None,
        "strengths": ["Editing", "Natural light", "Texture"],
    },
    {
        "id": "soul",
        "name": "Kinograde Soul",
        "kind": "image",
        "tagline": "High-aesthetic photoreal stills",
        "cost": 2,
        "badge": None,
        "strengths": ["Fashion", "Editorial", "Skin detail"],
    },
    {
        "id": "soul-2",
        "name": "Soul 2.0",
        "kind": "image",
        "tagline": "The next-generation Soul aesthetic",
        "cost": 3,
        "badge": "new",
        "strengths": ["Aesthetic", "Portraits", "Grade"],
    },
]

CAMERA_MOVES: list[dict[str, str]] = [
    {"id": "dolly-in", "name": "Dolly In", "grouping": "Push & pull",
     "fragment": "camera dollies smoothly in toward the subject"},
    {"id": "dolly-out", "name": "Dolly Out", "grouping": "Push & pull",
     "fragment": "camera dollies steadily away from the subject"},
    {"id": "super-dolly-in", "name": "Super Dolly In", "grouping": "Push & pull",
     "fragment": "extreme fast dolly push straight into the subject"},
    {"id": "crash-zoom-in", "name": "Crash Zoom In", "grouping": "Push & pull",
     "fragment": "violent crash zoom snapping in on the subject"},
    {"id": "crash-zoom-out", "name": "Crash Zoom Out", "grouping": "Push & pull",
     "fragment": "violent crash zoom snapping out from the subject"},
    {"id": "dolly-zoom", "name": "Dolly Zoom", "grouping": "Push & pull",
     "fragment": "vertigo dolly zoom, background warps while subject stays fixed"},
    {"id": "orbit-360", "name": "360 Orbit", "grouping": "Orbit & arc",
     "fragment": "camera orbits a full 360 degrees around the subject"},
    {"id": "arc-shot", "name": "Arc Shot", "grouping": "Orbit & arc",
     "fragment": "camera arcs laterally around the subject"},
    {"id": "lazy-susan", "name": "Lazy Susan", "grouping": "Orbit & arc",
     "fragment": "subject rotates on a turntable, camera locked off"},
    {"id": "bullet-time", "name": "Bullet Time", "grouping": "Orbit & arc",
     "fragment": "bullet time, frozen action with the camera sweeping around"},
    {"id": "crane-up", "name": "Crane Up", "grouping": "Crane & drone",
     "fragment": "camera cranes up and away, revealing the wider scene"},
    {"id": "crane-down", "name": "Crane Down", "grouping": "Crane & drone",
     "fragment": "camera cranes down toward the subject"},
    {"id": "fpv-drone", "name": "FPV Drone", "grouping": "Crane & drone",
     "fragment": "aggressive FPV drone flight weaving through the scene"},
    {"id": "overhead", "name": "Overhead", "grouping": "Crane & drone",
     "fragment": "top-down overhead shot looking straight down"},
    {"id": "earth-zoom-out", "name": "Earth Zoom Out", "grouping": "Crane & drone",
     "fragment": "continuous zoom out from the subject all the way to orbit"},
    {"id": "whip-pan", "name": "Whip Pan", "grouping": "Pan & tilt",
     "fragment": "fast whip pan with motion blur"},
    {"id": "tilt-down", "name": "Tilt Down", "grouping": "Pan & tilt",
     "fragment": "camera tilts down across the subject"},
    {"id": "pan-left", "name": "Pan Left", "grouping": "Pan & tilt",
     "fragment": "slow deliberate pan to the left"},
    {"id": "snap-zoom", "name": "Snap Zoom", "grouping": "Pan & tilt",
     "fragment": "snap zoom punching in one stop"},
    {"id": "handheld", "name": "Handheld", "grouping": "Rig & feel",
     "fragment": "raw handheld camera with natural shake"},
    {"id": "snorricam", "name": "Snorricam", "grouping": "Rig & feel",
     "fragment": "snorricam rig, subject fixed to frame while the world moves"},
    {"id": "robo-arm", "name": "Robo Arm", "grouping": "Rig & feel",
     "fragment": "precise robotic arm move, impossibly smooth"},
    {"id": "object-pov", "name": "Object POV", "grouping": "Rig & feel",
     "fragment": "point of view shot from the object itself"},
    {"id": "dutch-angle", "name": "Dutch Angle", "grouping": "Rig & feel",
     "fragment": "canted dutch angle framing"},
    {"id": "focus-change", "name": "Focus Change", "grouping": "Lens",
     "fragment": "rack focus from foreground to background"},
    {"id": "fisheye", "name": "Fisheye", "grouping": "Lens",
     "fragment": "extreme fisheye lens distortion"},
    {"id": "hyperlapse", "name": "Hyperlapse", "grouping": "Lens",
     "fragment": "hyperlapse with the camera travelling through space"},
    {"id": "glam", "name": "Glam", "grouping": "Lens",
     "fragment": "glossy beauty-campaign move with soft glamour lighting"},
]

EFFECTS: list[dict[str, str]] = [
    {"id": "vanish", "name": "Vanish", "grouping": "Transformation",
     "fragment": "the subject disintegrates and vanishes into particles"},
    {"id": "melting", "name": "Melting", "grouping": "Transformation",
     "fragment": "the subject melts and deforms like hot wax"},
    {"id": "world-morphing", "name": "World Morphing", "grouping": "Transformation",
     "fragment": "the entire world morphs into a different environment"},
    {"id": "cutout", "name": "Cutout", "grouping": "Transformation",
     "fragment": "the subject becomes a paper cutout lifted out of the scene"},
    {"id": "clones", "name": "Clones", "grouping": "Transformation",
     "fragment": "the subject splits into multiple synchronized clones"},
    {"id": "infinite-clones", "name": "Infinite Clones", "grouping": "Transformation",
     "fragment": "endless recursive clones receding into the distance"},
    {"id": "burning-man", "name": "Burning Man", "grouping": "Spectacle",
     "fragment": "the subject ignites in controlled cinematic flame"},
    {"id": "smash-and-grab", "name": "Smash and Grab", "grouping": "Spectacle",
     "fragment": "glass shatters as the subject smashes through"},
    {"id": "street-colossus", "name": "Street Colossus", "grouping": "Spectacle",
     "fragment": "the subject becomes a colossal giant towering over the street"},
    {"id": "particles", "name": "Particles", "grouping": "Spectacle",
     "fragment": "the subject is swept through a storm of glowing particles"},
    {"id": "architecture-wave", "name": "Architecture Wave", "grouping": "Spectacle",
     "fragment": "buildings ripple and wave like liquid"},
    {"id": "frozen-in-motion", "name": "Frozen in Motion", "grouping": "Time",
     "fragment": "everything freezes mid-motion while the camera keeps moving"},
    {"id": "stop-world", "name": "Stop World", "grouping": "Time",
     "fragment": "the world stops while the subject keeps moving freely"},
    {"id": "lidar-transition", "name": "Lidar Transition", "grouping": "Time",
     "fragment": "the scene resolves from a lidar point cloud into full image"},
    {"id": "moonwalk", "name": "Moonwalk", "grouping": "Performance",
     "fragment": "the subject moonwalks with effortless control"},
    {"id": "act-natural", "name": "Act Natural", "grouping": "Performance",
     "fragment": "the subject moves with relaxed, unposed naturalism"},
    {"id": "superstar", "name": "Superstar", "grouping": "Performance",
     "fragment": "the subject walks a flashbulb-lit red carpet like a superstar"},
    {"id": "wild-ride", "name": "Wild Ride", "grouping": "Performance",
     "fragment": "chaotic high-speed ride with the subject hanging on"},
    {"id": "high-flip", "name": "High Flip", "grouping": "Performance",
     "fragment": "the subject launches into a high acrobatic flip"},
    {"id": "comic", "name": "Comic", "grouping": "Style",
     "fragment": "rendered as inked comic book panels with halftone"},
    {"id": "lsd", "name": "LSD", "grouping": "Style",
     "fragment": "saturated kaleidoscopic psychedelic distortion"},
    {"id": "pearl-earring", "name": "Pearl Earring", "grouping": "Style",
     "fragment": "reimagined as a Dutch golden age oil portrait"},
    {"id": "scrapbook-collage", "name": "Scrapbook Collage", "grouping": "Style",
     "fragment": "torn paper scrapbook collage with tape and handwriting"},
    {"id": "blue-depth", "name": "Blue Depth", "grouping": "Style",
     "fragment": "deep monochrome blue grade with heavy atmospheric depth"},
]

FILM_SETUPS: list[dict[str, str]] = [
    {"id": "35mm", "name": "35mm Film", "grouping": "Format",
     "fragment": "shot on 35mm film with natural grain"},
    {"id": "anamorphic", "name": "Anamorphic", "grouping": "Format",
     "fragment": "anamorphic lenses with horizontal flares and oval bokeh"},
    {"id": "super-8", "name": "Super 8", "grouping": "Format",
     "fragment": "Super 8 home-movie texture, soft and grainy"},
    {"id": "imax", "name": "IMAX", "grouping": "Format",
     "fragment": "IMAX large-format clarity and depth"},
    {"id": "vhs", "name": "VHS", "grouping": "Format",
     "fragment": "degraded VHS tape with scanlines and colour bleed"},
    {"id": "documentary", "name": "Documentary", "grouping": "Treatment",
     "fragment": "observational documentary realism"},
    {"id": "studio-clean", "name": "Studio Clean", "grouping": "Treatment",
     "fragment": "clean studio capture, seamless backdrop"},
    {"id": "archival", "name": "Archival", "grouping": "Treatment",
     "fragment": "archival footage, faded and time-worn"},
]

COLOR_PALETTES: list[dict[str, str]] = [
    {"id": "teal-orange", "name": "Teal & Orange", "grouping": "Graded",
     "fragment": "teal and orange blockbuster grade"},
    {"id": "bleach-bypass", "name": "Bleach Bypass", "grouping": "Graded",
     "fragment": "bleach bypass, desaturated with crushed blacks"},
    {"id": "neon-noir", "name": "Neon Noir", "grouping": "Graded",
     "fragment": "neon noir palette, magenta and cyan against black"},
    {"id": "golden", "name": "Golden", "grouping": "Graded",
     "fragment": "warm golden palette, amber highlights"},
    {"id": "monochrome", "name": "Monochrome", "grouping": "Minimal",
     "fragment": "black and white with deep contrast"},
    {"id": "pastel", "name": "Pastel", "grouping": "Minimal",
     "fragment": "soft pastel palette, low saturation"},
    {"id": "earth", "name": "Earth", "grouping": "Minimal",
     "fragment": "muted earth tones, ochre and moss"},
    {"id": "technicolor", "name": "Technicolor", "grouping": "Saturated",
     "fragment": "vivid three-strip Technicolor saturation"},
]

LIGHTING: list[dict[str, str]] = [
    {"id": "natural", "name": "Natural", "grouping": "Daylight",
     "fragment": "soft natural daylight"},
    {"id": "golden-hour", "name": "Golden Hour", "grouping": "Daylight",
     "fragment": "low golden-hour sun, long shadows"},
    {"id": "overcast", "name": "Overcast", "grouping": "Daylight",
     "fragment": "flat overcast light, no hard shadows"},
    {"id": "hard-flash", "name": "Hard Flash", "grouping": "Artificial",
     "fragment": "harsh direct on-camera flash"},
    {"id": "neon", "name": "Neon", "grouping": "Artificial",
     "fragment": "coloured neon practical lighting"},
    {"id": "candlelit", "name": "Candlelit", "grouping": "Artificial",
     "fragment": "warm candlelight, deep falloff"},
    {"id": "rembrandt", "name": "Rembrandt", "grouping": "Studio",
     "fragment": "Rembrandt key light with a triangle on the cheek"},
    {"id": "rim-light", "name": "Rim Light", "grouping": "Studio",
     "fragment": "strong rim light separating subject from background"},
    {"id": "silhouette", "name": "Silhouette", "grouping": "Studio",
     "fragment": "backlit silhouette against a bright field"},
]

PRESETS_BY_FAMILY: dict[str, list[dict[str, str]]] = {
    "camera": CAMERA_MOVES,
    "effect": EFFECTS,
    "film": FILM_SETUPS,
    "palette": COLOR_PALETTES,
    "light": LIGHTING,
}
