# Generated by Django 5.2.17 on 2026-09-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=8)),
                ('tagline', models.CharField(max_length=160)),
                ('cost', models.PositiveIntegerField()),
                ('badge', models.CharField(blank=True, max_length=16, null=True)),
                ('strengths', models.JSONField(default=list)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('family', models.CharField(choices=[('camera', 'Camera move'), ('effect', 'Effect'), ('film', 'Film setup'), ('palette', 'Colour palette'), ('light', 'Lighting')], db_index=True, max_length=8)),
                ('name', models.CharField(max_length=80)),
                ('grouping', models.CharField(max_length=40)),
                ('fragment', models.TextField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('family', 'position', 'id'),
            },
        ),
    ]
