# Generated by Django 5.2.17 on 2026-09-25 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('composed_prompt', models.TextField()),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=8)),
                ('aspect', models.CharField(max_length=8)),
                ('resolution', models.CharField(max_length=8)),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('sound', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('rendering', 'Rendering'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('seed', models.CharField(max_length=32)),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('credits_spent', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.preset')),
                ('effect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.preset')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.preset')),
                ('light', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.preset')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='catalog.model')),
                ('palette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.preset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='studio.generation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['user', '-created_at'], name='studio_gene_user_id_b1581a_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['status', '-created_at'], name='studio_gene_status_fa1953_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'generation'), name='unique_like_per_user'),
        ),
    ]
