# Generated by Django 5.2.17 on 2026-09-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
