# Generated by Django 5.2.17 on 2026-09-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_generation_ready_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='queued_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
